config/routes.rb
  Rails.application.routes.draw do
    root'demo_pages#home'
    get 'sessions/new'
    get 'users/new'
    get '/help', to: 'demo_pages#help'
    get '/about', to: 'demo_pages#about'
    get '/signup', to: 'users#signup'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    post '/signup',  to: 'users#create'
    delete 'logout', to:'sessions#destroy'
    get '/edit', to:'users#edit'
    get '/search', to: 'users#index'

    get '/entry', to: 'demo_pages#entry'
    get '/show', to: 'demo_pages#show'
    
    get '/comment', to: 'comments#index'
    resources :users do
    member do
      get :following, :followers
    end
  end
    resources :microposts
    resources :relationships, only: [:create, :destroy]
    resources :comments
  end

app/models/user.rb
  class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
    attr_accessor :remember_token
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: {maximum: 100,minimum: 3}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
    validates :email, presence: true,length: {maximum: 100} ,format:{with: VALID_EMAIL_REGEX},
                    uniqueness: { case_sensitive: false }  
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
   self.per_page =15
     # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

    # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

   # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

   # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
   
  # Returns a user's status feed.
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

   # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end
 def self.search(pattern)
    if pattern.blank? 
      all
    else
      where('name or email LIKE ?', "%#{pattern}%")
    end
  end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
    before_action :correct_user,   only: [:edit, :update]
    before_action :admin_user,     only: :destroy
  def signup 
    @user=User.new    
  end
   
     def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted " 
    redirect_to users_url
  end
  def show

    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])

    
  end

  def show_comment
      @user = User.find(params[:id])
    @microposts = Micropost.paginate(page: params[:page])
  end
    def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  def create
    @user=User.new(user_params)
    if @user.save
      flash[:success]='register successfully!'
      redirect_to @user
    else
      render 'signup'
    end
  end

  def index
   
     @users = User.paginate(page: params[:page])
     @search = User.search(params[:search])
  end

   def edit
    @user = User.find(params[:id])
   end

  def following
    @title = "Following"
    @user  = User.find params[:id]
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

   private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end 

     # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        # store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

      # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end
  

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
def sortable(column, title = nil)
  title ||= column.titleize
  css_class = column == sort_column ? "current #{sort_direction}" : nil
  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
end
  
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <%= link_to user.email, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
                                      <i class="glyphicon glyphicon-trash"></i>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages'  , object: f.object %>

      <%= f.label :name %><em class="oblige">*</em>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %><em class="oblige">*</em>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %><em class="oblige">*</em><em>(6 characters minimum)</em>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %><em class="oblige">*</em>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<h1>All users</h1>

       
  <%= form_tag users_path, :method => 'get' do %>

  <p>
    <%= text_field_tag :search, params[:search] ,class:"form-control input-sm " %>  
    <span class="glyphicon glyphicon-search"></span>
    <%= submit_tag "Search", :name => nil ,class:"btn_search btn-primary "%>
  </p>
<% end %>
</div>
</div>
</div>
  <%= will_paginate %>
  <ul class="users">
  <%= render @search %>
</ul>

<%= will_paginate %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
     <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Entries (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>

app/views/users/signup.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
     <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %><em class="oblige">*</em>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %><em class="oblige">*</em>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %><em class="oblige">*</em><em>(6 characters minimum)</em>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %><em class="oblige">*</em>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>