config/routes.rb
  Rails.application.routes.draw do
    root'demo_pages#home'
    get 'sessions/new'
    get 'users/new'
    get '/help', to: 'demo_pages#help'
    get '/about', to: 'demo_pages#about'
    get '/signup', to: 'users#signup'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    post '/signup',  to: 'users#create'
    delete 'logout', to:'sessions#destroy'
    get '/edit', to:'users#edit'
    get '/search', to: 'users#index'

    get '/entry', to: 'demo_pages#entry'
    get '/show', to: 'demo_pages#show'
    
    get '/comment', to: 'comments#index'
    resources :users do
    member do
      get :following, :followers
    end
  end
    resources :microposts
    resources :relationships, only: [:create, :destroy]
    resources :comments
  end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :comments
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  # validates :title, presence: true, length: { maximum: 40,minimum: 3 } 
  mount_uploader :picture, PictureUploader
  validates :content, presence: true, length: { maximum: 140,minimum: 3 } 
  self.per_page =10

   def self.search(pattern)
    if pattern.blank? 
      all
    else
      where('content or title  LIKE ?', "%#{pattern}%")
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  # before_action :logged_in_user, only: [:create, :destroy]
   before_action :correct_user,   only: [:destroy]

  def destroy
    correct_user
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
    
  end
  def show
    
    @micropost = Micropost.find_by_id params[:id]

    @comment=@micropost.comments.paginate(page: params[:page],per_page: 3)

  end
  # def index
  #   @search = MicropostsController.search(params[:search])    
  # end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'demo_pages/entry'
    end
  end



  private

    def micropost_params
      params.require(:micropost).permit(:content,:title, :picture)
    end

     def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end


end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<div class="boder">
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>

  <i><b><span class="title"><%= micropost.title %></span></b></i>
  <p class="content"><%= micropost.content %></p>
 <%= image_tag micropost.picture.url if micropost.picture? %>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
        <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
                                       <i class="glyphicon glyphicon-trash"></i>
    <% end %>
  </span>
 
   <li>  
    <% if logged_in? %>
    
     <%= link_to "comment", micropost_path(micropost)%>
   <% else%>
     <%= link_to "view comment", micropost_path(micropost)  %>  
        
    <%end %>


  </li>

</li>

</div>

app/views/microposts/_show_comment.html.erb
  <!-- <%= will_paginate @comment %> -->

 <% if @comment.any?%>
   <% @comment.each do |comment| %>
   <div class="boder_comment">
     <h3><%= comment.content%> </h3>
     <h6><b>comment by:</b><%= comment.user.name%></h6>
     <h6><b>created_at:</b><%= comment.created_at%> </h6>
     </div>
   <% end %> 
    <%else%>
   <p class="messages"><i><b>Entry nay chua co comment nao!</b></i></p>
<%end%>

  <%= will_paginate @comment %>

app/views/microposts/show.html.erb
  <% if logged_in? %>
    <h5>created by:<%=@micropost.user.name%></h5>
    <h6>created_at:<%= @micropost.created_at %></h6>
    <h1><%= @micropost.title %></h1>
    <h2><%= @micropost.content %></h2>
 
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for Comment.new  do |f| %>
      
          <%= render 'shared/error_messages', object: f.object %>
           
              <%= f.label :content, 'Enter your comment:' %>
              <%= f.text_area :content,class:'form-control'  %>
              <%= f.hidden_field :micropost_id, value: @micropost.id %>
              <small class="label label-warning">Cannot be blank</small>
              <%= f.submit 'Submit', class: "btn btn-primary" %>
       <% end %>
     </div>
    </div>
    <%= render 'show_comment' %>
 <% else%>
     <h5>created by:<%=@micropost.user.name%></h5>
    <h6>created_at:<%= @micropost.created_at %></h6>
    <h1><%= @micropost.title %></h1>
    <h2><%= @micropost.content %></h2>
       <%= render 'show_comment' %>
  <%end %>