config/routes.rb
  Rails.application.routes.draw do
    root'demo_pages#home'
    get 'sessions/new'
    get 'users/new'
    get '/help', to: 'demo_pages#help'
    get '/about', to: 'demo_pages#about'
    get '/signup', to: 'users#signup'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    post '/signup',  to: 'users#create'
    delete 'logout', to:'sessions#destroy'
    get '/edit', to:'users#edit'
    get '/search', to: 'users#index'

    get '/entry', to: 'demo_pages#entry'
    get '/show', to: 'demo_pages#show'
    
    get '/comment', to: 'comments#index'
    resources :users do
    member do
      get :following, :followers
    end
  end
    resources :microposts
    resources :relationships, only: [:create, :destroy]
    resources :comments
  end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   copyright: <a href="http://www.railstutorial.org/" target="abcd">Ruby on Rails Tutorial</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "tvq bog", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>

        <!-- <li><%= link_to "Entry", entry_path %></li> -->
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             Entry <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
               <%if logged_in?%>
              <li><%= link_to "create entry", entry_path %></li>
              <li><%= link_to "show entry", current_user %></li>
              <li><%= link_to "show comment", show_path %></li>
               <%else%>
               <li><%= link_to "show entry", show_path %></li>
               <%end%>
            </ul>
          </li>

        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
           <li><%= link_to "Users", users_path %></li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Update", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key,value|%>
       <div class="alert alert-<%= key %>"><%= value %></div>
      <% end -%>
      <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>